[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "socha"
requires-python = ">=3.7"
version = "0.9.8"
authors = [
    { name = "FalconsSky", email = "stu222782@mail.uni-kiel.de" },
]
description = "This is the package for the Software-Challenge Germany 2023. This Season the game will be 'Hey, danke für den Fisch' a.k.a. 'Penguins' in short."
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "xsdata==22.7"
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
]


[tool.maturin]
python-source = "python"
exclude = [
    ".github",
    "docs",
    "tests",
    "logic.py",
    "readthedocs.yaml"
]
[project.urls]
"Bug Tracker" = "https://github.com/FalconsSky/Software-Challenge-Python-Client/issues"