---
name: "pre-release"

on:
  push:
    tags:
      - v*

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Exit if not on dev branch
        if: endsWith(github.ref, 'dev') == false
        run: exit -1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build
        run: python -m build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/socha*